#!/bin/bash
AlgoDisabled[equihash]="AlgoDisabled:equihash:*:GPU-84f7ca95-d215-185d-7b27-a7f017e776fb"
AlgoDisabled2="AlgoDisabled:equihash:GPU-84f7ca95-d215-185d-7b27-a7f017e776fb:*:GPU-742cb121-baad-f7c4-0314-cfec63c6ec70"
#read -a AlgoName <<<${AlgoDisabled[equihash]//:/ }
read -a AlgoName <<<${AlgoDisabled2//:/ }
#declare -p AlgoName
if [ ${#AlgoDisabled[${AlgoName[1]}]} -gt 0 ]; then
    read -a sortThem <<<${AlgoDisabled[${AlgoName[1]}]//:/ }
    sortThem=("${sortThem[@]:2}" "${AlgoName[@]:2}")
    rm -f sortThem
    for sortIt in "${sortThem[@]}"; do
	echo "$sortIt" >>sortThem
    done
    rest=$(cat sortThem | sort -u )
    #readarray -t tst <<<${rest//\n/ }
    readarray -t tst <<<${rest//\n/ }
fi
echo ":${tst// /:}"
